name: daily-trends

on:
  workflow_dispatch:
  schedule:
    - cron: "30 13 * * *"  # 08:30 America/Chicago

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install -r src/requirements.txt
          python -m spacy download en_core_web_sm

      - name: Run
        env:
          USE_TRENDS: "0"         # set to "1" if you want Google Trends
          SEND_TELEGRAM: "${{ secrets.SEND_TELEGRAM }}" # "1" to enable
          TELEGRAM_TOKEN: "${{ secrets.TELEGRAM_TOKEN }}"
          TELEGRAM_CHAT_ID: "${{ secrets.TELEGRAM_CHAT_ID }}"
        run: |
          python src/main.py

      - name: Commit results
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add -A
          git commit -m "Daily update" || echo "No changes"
          git push
